# Detector Configuration File

# Model Configuration
model:
  onnx_file: "models/model.onnx"           # Relative to detector directory
  img_size: 640
  conf_thres: 0.6
  device: "cpu"  # Options: "cpu", "gpu"

# File Paths
paths:
  categories_file: "configs/categories.yaml" # Relative to detector directory
  default_image: "default/default_img.jpg"  # Relative to detector directory

# Inference Settings
inference:
  batch_size: 1
  max_detections: 100

# CLO Processing
clo:
  enabled: true
  values_file: "clo_values.yaml"     # Relative to detector directory

# Logging
logging:
  level: "WARNING"  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # Format with timestamp and level
  enable_console: true
  enable_file: false   # Explicitly disable file logging
  file: null           # No log file

# Postprocessing
postprocessing:
  enabled: false  # Enable temporal postprocessing for stable detections
  history_size: 5  # Number of frames to keep in memory
  expiry_seconds: 5.0  # How long to keep detections alive
  keep_alive_frames: 3  # Frames to keep detection alive during brief occlusions
  min_presence_ratio: 0.5  # Minimum ratio of frames a class must appear in
  load_rules_from_file: true  # Load thresholds and rules from separate file
  rules_file: "configs/postprocessing.yaml"
  # These will be overridden by rules file if load_rules_from_file is true
  conf_thresholds:
    default: 0.6
  valid_layers: {}

  # S3 Model Downloader Configuration

# AWS Configuration
# Credentials priority: config file > environment variables
# You can set credentials here or use environment variables
aws:
  region: us-east-1
  access_key_id: null  # Set your access key here or use AWS_ACCESS_KEY_ID env var
  secret_access_key: null  # Set your secret key here or use AWS_SECRET_ACCESS_KEY env var

# Download configurations
downloads:
  # Download ONNX model from computer vision datasets
  - bucket: computer-vision-datasets
    s3_path: models/model.onnx
    local_path: ./models/model.onnx

# Alternative: Use environment variables for AWS credentials
# Set these environment variables instead of hardcoding:
# export AWS_ACCESS_KEY_ID=your_access_key
# export AWS_SECRET_ACCESS_KEY=your_secret_key